### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by mikeal** [nodejs/iojs-tw#1]
Welcome, new localizations team :)

To get this team up and running you have a few initial tasks to accomplish:
- [x] Create a README.md for this repository, it should include:
  - [x] A "call to action" pointing to the Issue tracker for new translators to find tasks.
  - [x] A list of the team members.
  - [x] Instructions on how to log an issue to be added to this team.
- [x] Set the repository description. This should not be in English, it should be in the language for this community :)
- [x] Social Media
  - [x] Create a twitter account for this language. Share the password privately with the team.
  - [x] Create accounts on other social media popular in this language. Share the passwords private with the rest of the team.
  - [ ] Make sure you use these accounts not just to promote newly translated material but also to attract people in your community to help with translation tasks.
  - [ ] _Optional:_ If you plan to do a Google hangout w/ your localization team have @mikeal add you to the Google+ account so that it can post to the `iojs` YouTube channel. Once you are added there is [documentation on how to setup a hangout-on-air](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).
- [x] Finally, create a new Issue to translate and publish the [latest io.js post](https://medium.com/@iojs). Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

**Comment by poying** [comment]
Social Media 密碼的部份，要不要統一管理，記得以前 @clonn 有個專門放密碼的地方

**Comment by appleboy** [comment]
有申請了 iojs.tw 帳號？

**Comment by jessy1092** [comment]
Facebook 需要額外開 group 嗎?  還是一樣使用 node.js 台灣討論就好?

**Comment by poying** [comment]
@appleboy 不知道 iojs.tw 被誰買走，twitter 的話應該是用 `iojs_tw`

**Comment by clonn** [comment]
如果要的話可以沿用 nodejs.tw 網域，同時發布關注 node 及 iojs。

**Comment by appleboy** [comment]
我覺得沿用 nodejs.tw 網域即可

**Comment by dca** [comment]
沿用 `nodejs.tw` +1

另外 `iojs.tw` 的註冊人看起來有在 Facebook 社團，有需要的話可能可以連絡看看

**Comment by poying** [comment]
Social Media 部分請到 #5 討論

**Comment by tk120404** [comment]
@mikeal  Can you please close this issue if this is not an issue any more?
