### ISSUE TITLE
建議先取消 guideline 制定

### ISSUE THREAD

**Issue by cfsghost** [nodejs/iojs-tw#10]
由於現在極缺少人與內容，不應該一開始就進行制定太細的管理規則與規範。

應當遵從 io.js 社群的 open governance model 模式，讓想要貢獻的人可以自由貢獻。

在 OGM 這樣的管理模式下，規則和規範是建構於貢獻者所貢獻的成果之上，然後才開始進行的討論與修正。

因此，要先選坑跳接受管理才開始貢獻也不必要，鼓勵網友進行直接且實質的貢獻，並發出 PR ，才是眼前最重要的事。

讓有熱情、想做事的出來，比一開始就搞管理框架來得更妥當。

註：看到別的國家地區正在努力翻譯，而我們卻正在努力寫 guideline，所以才有此建議。

**Comment by appleboy** [comment]
就先制定到這邊，大家有空就幫忙翻譯，翻譯準則可以慢慢制定，我相信目前的制定對想加入翻譯的朋友們是非常有幫助的。

**Comment by clonn** [comment]
因為是翻譯，所以在中文及英文，那些要翻譯，那些不翻譯基本上這個 guidelines 是會需要的。

建議保留目前的 guidelines. 目前 guidelines 資料是由之前 node.js Taiwan 大家所集結下來的精華。

**Comment by cfsghost** [comment]
總之，guideline 到此為止就好，不應再多做更新。

現在是零到一的階段，人力缺少，應該先就翻譯者本身的習慣進行（只要是台灣的翻譯者，應該不會有太多問題），不應在一開始強加太多限制。

重點是，guideline 是給要翻譯的人看的，讓有心花時間投入翻譯的人自行討論及制定更新 guideline 比什麼都還重要。

另外一提，一邊翻譯一邊看哪些參考 guideline 是很累的一件事，這不應該發生在一開始什麼都沒有的時候。（所以像是我就根本沒在看）

Caesar Chi notifications@github.com 於 2015年2月9日 下午12:03 寫道：

**Comment by clonn** [comment]
對於新手來說這是必要的。

特別是現在才剛開始，所以正需要 mini guidelines, 讓新手容易開始進行。

所以取中間值，只採用是有必要的 guidelines ，以
- 最快速開發
- 最低進入門檻

兩個思考點為優先。

**Comment by dca** [comment]
感謝上面各位的貢獻，讓我睡醒之後 翻譯也有了、guidelines 也有了！

感謝幾位搶先動手的效率，讓選擇先睡覺的我倍感慚愧。
也感謝 guidelines 的出現，讓新手如我可以有個入門指南以免被覺得來亂的。

這邊先幫大家做個關閉。
如果後面還有什麼可以幫忙的，請大家再發發 issue 提點我啊 :+1:
