### ISSUE TITLE
翻譯 2015.02.06 Weekly report

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#11]
我來負責翻譯 [2015.02.06 週報](https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4) ref #8

**Comment by cfsghost** [comment]
我正好也在翻，不過才剛開始，所以就先交給你啦！XD (嘴砲模式)

**Comment by appleboy** [comment]
@cfsghost 好 XD
