### ISSUE TITLE
翻譯 npm-weekly-22

### ISSUE THREAD

**Issue by chentsulin** [nodejs/iojs-tw#126]
草稿：https://github.com/nodejs/iojs-tw/blob/master/source/_drafts/npm-weekly-22.md

**Comment by appleboy** [comment]
Closed via #127

**Comment by chentsulin** [comment]
話說 22 沒有發佈？

**Comment by appleboy** [comment]
@chentsulin 一直存在 local 端，忘記 `git add`，剛剛已經 publish 了。待會就可以看到資料了
