### ISSUE TITLE
Proposal: rename the nodejs/iojs-tw WG to nodejs/nodejs-zh-TW

### ISSUE THREAD

**Issue by srl295** [nodejs/iojs-tw#138]
Dear members of the io.js Chinese (Taiwan) WG `iojs-tw`

It is proposed to rename this repo to:

   [nodejs/nodejs-zh-TW](https://github.com/nodejs/nodejs-zh-TW/)

As part of the io.js and node.js convergence, node.js releases are now based on the codebase and user base of the converged node.js and io.js communities. A number of the resources and repositories have already been renamed.
In the absence of objections or other discussion, this rename will occur on or after [Oct 28, 2015](http://time.is/1200AM_28_Oct_2015_in_GMT?iojs-rename)

However, active language working groups should take ownership of this issue and discuss/dispose of it according to their own processes.

For more information or to discuss the overall issue, please see and comment on https://github.com/nodejs/node/issues/2525

This statement was authorized by the Node.js TSC

Cc: @nodejs/iojs-tw

**Comment by srl295** [comment]
Please note as with nodejs/iojs-cn#173 my proposal includes language and region in your WG's new name. There were only two groups that used a region name as group name, all others were strictly language.

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by jihchi** [comment]
:+1:

**Comment by appleboy** [comment]
:+1: Agree ..

**Comment by jessy1092** [comment]
:+1: Nice

**Comment by josyeh** [comment]
:+1:

**Comment by chentsulin** [comment]
:+1:

**Comment by imZack** [comment]
:+1:

**Comment by zack9433** [comment]
:+1:

**Comment by Rukeith** [comment]
:+1:

**Comment by srl295** [comment]
Please see the discussion in iojs-CN in the issue I linked to. Should this
group be zh-TW or really zh-Hant (traditional orthography regardless of
location)?

**Comment by jessy1092** [comment]
@srl295 The original WG purpose is for **localizations** team. I prefer zh-TW. :)

**Comment by clonn** [comment]
:+1:

**Comment by siygle** [comment]
+1 zh-TW

**Comment by appleboy** [comment]
@srl295 Done

**Comment by srl295** [comment]
@appleboy Thanks
