### ISSUE TITLE
協助翻譯 Change log

### ISSUE THREAD

**Issue by jessy1092** [nodejs/iojs-tw#16]
每次 iojs release 的更新記錄 
https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md

iojs-cn 已經把 1.0.0 以來的 更新紀錄翻完了，可以參考 
https://github.com/iojs/iojs-cn/blob/master/CHANGELOG.md 

下次的更新紀錄應該是 1.2.0
https://github.com/iojs/io.js/issues/768

我們要參考 iojs-cn 的模式，直接複製一份 CHANGELOG.md 過來嗎?
或者有什麼更好的模式?

**Comment by clonn** [comment]
先求有再求好的模式，建議是先把簡體轉成繁體。 XDDDDD

不過 `changelog` 翻譯的必要性，這邊我沒有想法，因為 changelog 大部分都是官方推出直接就看原文資料了。 XDDDDD

**Comment by clonn** [comment]
如果有其他 changelog 需要翻譯，再請增加上去 issue 。

目前先將這個 issue 關閉。
