### ISSUE TITLE
製作 iojs-tw 網站

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#23]
看到對面已經完成了 http://iojs.github.io/iojs-cn/ 我們這邊是不是也該弄個小型網站，至少翻譯的文章可以有 Web 介面可以觀看。

大家不知道意見如何？
- [x] 合併 hexo 到 master 分支 #26 
- [x] 選擇 [hexo theme](https://github.com/hexojs/hexo/wiki/Themes) #34 
- [x] 定義發文格式
- [x] 自動 Deploy 到 `gh-pages`

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by jessy1092** [comment]
贊成 :+1:

**Comment by siygle** [comment]
:+1:

**Comment by dca** [comment]
目前想到兩個方案，
1. 跟 iojs-cn 一樣使用 [jekyll](http://jekyllrb.com/)，需要 ruby 環境
2. 使用 Node.js 方案 [Hexo](http://hexo.io/) (或其他)
3. 請大家推薦其他解法

不知道各位有沒有什麼想法？

**Comment by siygle** [comment]
推 Hexo，而且我們有原作者在啊 ;p @tommy351 

iojs-cn 的做法我也覺得不錯，[官網 i18n 好像也起來了](https://iojs.org/zh_TW/)
所以這邊就轉做 iojs-tw 文章的網站?

**Comment by appleboy** [comment]
@Ferrari 對，沒錯，官網那邊，他們會跑更新，基本上那邊就不用 mirror 到我們這邊

這邊就翻譯文件，放上 Web，然後固定有人去分享即可

**Comment by appleboy** [comment]
另外 Hexo +1

**Comment by tommy351** [comment]
沒想到有人推 Hexo，那就讓我也老王賣瓜的自推一下 Hexo 吧

**Comment by clonn** [comment]
推 hexo。這邊是先套用大陸的樣式直接進行嗎？還是有設計可以入場協助？
2015/2/12 下午6:31 於 "Tommy Chen" notifications@github.com 寫道：

**Comment by dca** [comment]
只好請作者技術支援一下了？ XDDDDD @tommy351

**Comment by appleboy** [comment]
大家先來選個 Theme 吧

https://github.com/hexojs/hexo/wiki/Themes

**Comment by appleboy** [comment]
http://kywk.github.io/hexo-theme-biture/ 這個感覺簡單好懂

**Comment by appleboy** [comment]
http://iojs.nodejs.tw/ 先弄一版，新的 branch 會 rebase 到 master branch

請先參考 source code https://github.com/iojs/iojs-tw/tree/hexo （目前尚未合併）

以後不需要分 weekly 或 articles 目錄，都直接放到 `source/_posts` 內

文章格式 `:year-:month-:day-:title.md`

**Comment by jessy1092** [comment]
@appleboy ++  迅速阿~

**Comment by appleboy** [comment]
之後 weekly 或 article 可以用 tag 來標記。

**Comment by appleboy** [comment]
我在最上面列了 Todo list，應該沒這麼少，想到就增加，有問題盡量提出

**Comment by tommy351** [comment]
自動 deploy 可參考：http://zespia.tw/blog/2015/01/21/continuous-deployment-to-github-with-travis/

**Comment by appleboy** [comment]
@tommy351 Great article. 為了解決 CNAME 問題，我把 hexo upgrade 到 3.0.0 RC3 XD

**Comment by appleboy** [comment]
Auto deploy 完成 cc @tommy351

**Comment by appleboy** [comment]
新增 About us 文章 http://tw.iojs.org/about-us/index.html

可以從 https://github.com/iojs/iojs-tw/blob/master/source/about-us/index.md 修改

內容是從 Readme 搬過來的。

**Comment by appleboy** [comment]
這篇討論應該結束了，目前網站使用 hexo framework 持續運作中，如果有其他問題請另外開 issue。
