### ISSUE TITLE
翻譯 Getting to know io.js

### ISSUE THREAD

**Issue by clonn** [nodejs/iojs-tw#24]
從 https://github.com/iojs/iojs-cn/issues/48 看到，雖然不是官方，但是值得一讀的文章

https://developer.atlassian.com/blog/2015/01/getting-to-know-iojs/

另外提出來，是否都只能翻譯官方的文章，其他相關的 `iojs` 文章是否也要翻譯！？

**Comment by appleboy** [comment]
我覺得好文就翻譯，不需要限定是不是官方的

**Comment by CYBAI** [comment]
:+1:

**Comment by jessy1092** [comment]
好文就翻譯+1

**Comment by jessy1092** [comment]
突然看到，其實 @appleboy  翻完了嘛~  XD
http://blog.wu-boy.com/2015/02/getting-to-know-io-js/

**Comment by dca** [comment]
同意好文就翻 :+1: 

未來如果有把這邊的成果做成網頁的話，可以運用這些內容來做更多推廣

**Comment by appleboy** [comment]
https://github.com/iojs/iojs-tw/blob/master/source/_drafts/getting-to-know-io-js.md 有人要認領嗎？XD

**Comment by clonn** [comment]
糟糕，我好像應該先發出  pr 才對。

目前先進行第一段。後續請大家接手。

**Comment by appleboy** [comment]
@clonn :+1:

**Comment by clonn** [comment]
目前已經接手 ，請大家幫忙補遺不足之處。

**Comment by appleboy** [comment]
http://tw.iojs.org/2015/02/13/getting-to-know-io-js/

覺得翻譯有問題就直接 PR
