### ISSUE TITLE
iojs.tw 網址

### ISSUE THREAD

**Issue by chinghanho** [nodejs/iojs-tw#25]
Hi

iojs.tw 是我註冊的。

當初想拿來丟一些研究 node.js / io.js 的資料，但短時間內應該沒時間弄，如果社群有計劃要幹點什麼，這個網址我願意提供給社群使用，需要設定什麼跟我說一聲就可以了。 :)

**Comment by jihchi** [comment]
Awesome

**Comment by appleboy** [comment]
Good Job 非常需要阿 @chinghanho 感謝您

@clonn 可否幫忙設定 CNAME?

**Comment by chinghanho** [comment]
http://iojs.tw 已經加 CNAME 指到 iojs.github.io 囉！

Github Pages 應該是這樣設定的吧？ :blush:

**Comment by siygle** [comment]
:+1: Really appreciate!!

應該再改 gh-pages 下面的CNAME 就可以了?

**Comment by clonn** [comment]
感謝大大無私
2015/2/13 下午12:53 於 "Shih-Yung Lee" notifications@github.com 寫道：

**Comment by tommy351** [comment]
一級網域應該得設定 A record？
https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/

**Comment by appleboy** [comment]
@tommy351 是對的。

@chinghanho 可否幫忙重新設定。

**Comment by chinghanho** [comment]
OK，重新設定好了。

加兩筆 A record 分別到 192.30.252.153 和 192.30.252.154。

**Comment by appleboy** [comment]
@chinghanho 不好意思又來麻煩您了

你可以將 iojs.tw 指向 tw.iojs.org

官方提供 sub domain 讓我們使用了

謝謝

**Comment by chinghanho** [comment]
OK 了，http://iojs.tw 已設定 301 到 http://tw.iojs.org

**Comment by appleboy** [comment]
@chinghanho Thanks.

**Comment by clonn** [comment]
iojs.nodejs.tw 也已經設定完成囉。
