### ISSUE TITLE
選擇部落格樣式

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#34]
目前預設就 Hexo.js 樣式，大家可以從 https://github.com/hexojs/hexo/wiki/themes 選擇

不知道大家有無意見，目前我只有修改原本的 quote css 而已。

ref #23

**Comment by poying** [comment]
casper

**Comment by cfsghost** [comment]
casper++

**Comment by appleboy** [comment]
Closed via 770450efb7bec24ddd593b6763a0d930d889e8b5

Done! refer: http://tw.iojs.org/
