### ISSUE TITLE
Turn off Travis build on pull requests?

### ISSUE THREAD

**Issue by PeterDaveHello** [nodejs/iojs-tw#37]
看起來我們目前只是為了部署網站才使用這樣的服務而不是跑測試

另外Environment Variables也是設在Travis CI上面不顯示出來而不是直接放到.travis.yml裏面，PR沒辦法存取到那些資訊

所以我想Build pull requests這個功能應該是可以關掉了？

免得送PR的人看到Build failed被嚇到

PS：我目前還沒動這個設定

**Comment by appleboy** [comment]
已經在 travis 那邊關閉設定
