### ISSUE TITLE
流程

### ISSUE THREAD

**Issue by poying** [nodejs/iojs-tw#4]
是否需要一個統一的流程呢？像是 GitHub Flow

**Comment by appleboy** [comment]
不多說，一定是 Github Flow. XD

**Comment by appleboy** [comment]
補連結 [Github Flow](https://guides.github.com/introduction/flow/index.html)

**Comment by jessy1092** [comment]
Github Flow+1

**Comment by clonn** [comment]
採用 work flow + 1

**Comment by touhonoob** [comment]
請問要貢獻翻譯的話直接在這個repo開branch就好了嗎？
還是需要另外fork一份？

**Comment by cfsghost** [comment]
如果是 io.js 官方網站的翻譯的話，你先 fork 我這邊的 project 進行修改好了，因為我已經翻了一個版本出來了（翻不好請包涵），暫時可以統一由我這發 PR 到 upstream：
https://github.com/cfsghost/website

本來想說看能不能 fork 成這個 io.js-tw 的 branch，但發現好像不行，只好先 fork 成個人的 repo 來做。orz

**Comment by appleboy** [comment]
我本來還想複製過來此 repo 放到 gh-page branch。XD

**Comment by cfsghost** [comment]
樓上++

其實也可以，以後有人固定複製翻譯過的檔案到個人 repo 上發 PR 就好。XD

**Comment by cfsghost** [comment]
gh-pages 已上！

http://iojs.github.io/iojs-tw/

**Comment by appleboy** [comment]
@cfsghost 動作真快 :+1: 

有需要掛 iojs.tw domain 到 gh-pages？還是就用預設的 github.io 即可？

**Comment by cfsghost** [comment]
如果可以掛是最好，不過先等 upstream 的討論結果吧。:-P

**Comment by clonn** [comment]
我可以幫忙掛到 iojs.nodejs.tw 底下。

大家覺得這個網址如何？？？

**Comment by poying** [comment]
不錯啊!

**Comment by clonn** [comment]
已經更新上去，可以正常連線到繁體版本  http://iojs.nodejs.tw/

**Comment by appleboy** [comment]
已經統一走 github flow.
