### ISSUE TITLE
weekly 2015.02.20

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#44]
https://github.com/iojs/website/issues/188

https://medium.com/node-js-javascript/io-js-week-of-february-20th-2015-48486615980

**Comment by appleboy** [comment]
原文已經出來了 https://medium.com/node-js-javascript/io-js-week-of-february-20th-2015-48486615980

**Comment by chentsulin** [comment]
這篇我可以幫忙翻

**Comment by appleboy** [comment]
@chentsulin OK

**Comment by appleboy** [comment]
@chentsulin 我已經將原文放在 draft 目錄內了，請享用 ^^

**Comment by chentsulin** [comment]
已 pr #46

**Comment by appleboy** [comment]
closed via f0e125888f0debc7ffd18629da30996b95d6566c

**Comment by appleboy** [comment]
cc @dca @clonn @jessy1092 

請幫忙發佈到 twitter http://tw.iojs.org/2015/02/22/io-js-weekly-2015-02-20/
