### ISSUE TITLE
evangelism: Weekly Update Feb 27th

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#48]
轉發到這裡了

https://github.com/iojs/evangelism/issues/4

**Comment by chentsulin** [comment]
已發佈：
https://medium.com/node-js-javascript/io-js-week-of-february-17th-9422a589302a

**Comment by appleboy** [comment]
https://github.com/iojs/iojs-tw/commit/89252df51fc36879fac5290f07108bf2d1f1d4d2 

已經發好 drafs 請大家用此檔案翻譯

**Comment by siygle** [comment]
翻了一部分，有志者可以接手 xD https://github.com/iojs/iojs-tw/pull/52

**Comment by appleboy** [comment]
closed via https://github.com/iojs/iojs-tw/commit/cca0356c8fc5c8e407921246f12374cd782be9fe

cc @dca @clonn 

Link: http://tw.iojs.org/2015/03/07/io-js-week-of-february-27th/
