### ISSUE TITLE
social media 訂定

### ISSUE THREAD

**Issue by clonn** [nodejs/iojs-tw#5]
鑑於之前 node.js 已經已經有 social media 系列，列表如下，
- [https://twitter.com/NodejsTaiwan](https://twitter.com/NodejsTaiwan)
- [Node.js Taiwan  facebook 粉絲頁](https://www.facebook.com/NodeJS.tw)
- [Node.js Taiwan facebook 社團](https://www.facebook.com/groups/node.js.tw/?ref=bookmarks)
- [Node.js Taiwan Youtube](https://www.youtube.com/user/nodejsTaiwan)
- [Node.js Taiwan google plus](https://plus.google.com/106619802476745918068)

本次 io.js 其實也涵蓋於 node.js 本身，這邊建議會採用沿用的方式進行 io.js 以及 node.js 相關資料的宣傳。

**Comment by poying** [comment]
沿用 +1

**Comment by clonn** [comment]
我這邊也是覺得沿用  +1

另外還是要提出，目前缺少發佈人員。 XDDDD
歡迎跳坑 #2

**Comment by dca** [comment]
不說還真不知道有這麼多了 :+1:

**Comment by siygle** [comment]
沒有打算申請一個 @iojs_tw 的帳號嗎? ;p

不過根據 joyent 跟社群內近期的發言，未來 nodejs 跟 iojs 未必一直會是相同的東西。 XD

**Comment by clonn** [comment]
因為 node.js Taiwan 其實也會發布 io.js 相關資訊，實際運作上不會收到 joyent 干擾。（實際上是社群幫忙宣傳）

提出討論主要是擔心，項目太多，宣傳力量太少，無法維護。

以目前狀況，更重要是需要實際長期協助發布人員 XDDDD
 2015/2/9 下午1:54 於 "Shih-Yung Lee" notifications@github.com 寫道：

**Comment by siygle** [comment]
發佈人員我應該可以幫忙 ;p
不過有什麼發佈的準則嗎？ e.g. @official_iojs weekly or every new RP on iojs-tw?

**Comment by clonn** [comment]
沒有規則，只要發布即可。XDDD

要在多個不同 social media 窗口張貼資訊就是了.
2015/2/9 下午6:09 於 "Shih-Yung Lee" notifications@github.com 寫道：

**Comment by jessy1092** [comment]
發佈人員我也可以幫忙~   

目前想到可以同步翻 https://twitter.com/official_iojs

**Comment by appleboy** [comment]
https://twitter.com/official_iojs

看起來每個國家都申請 `iojs_xx` 這種帳號

**Comment by dca** [comment]
來報名一下，發發訊息什麼的我應該做得來 XD

**Comment by clonn** [comment]
目前已經將資料發佈給 @dca @jessy1092  。
先請兩位協助 facebook fans page, twitter 媒體發佈資料。

另外已經建立 

https://twitter.com/iojs_tw

歡迎大家發落。

**Comment by appleboy** [comment]
@clonn Account suspended for twitter?

**Comment by poying** [comment]
你嘗試查看的個人資料已被停用

**Comment by jessy1092** [comment]
剛重新啟用了，有可能太多不同 ip 同時登入，被 twitter 說是廣告帳號。 可以再試試看 XD

我先綁定我的手機號碼 讓他通過驗證   @clonn  @dca

**Comment by clonn** [comment]
@jessy1092  感謝，如果有需要再麻煩你的手機號碼 XD

**Comment by clonn** [comment]
目前社群資料分享由 @Ferrari @jessy1092 @dca  三人協助發佈，感謝各位認領。

先行 close 這個 issue
