### ISSUE TITLE
對於官方提的中文字

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#54]
https://github.com/iojs/website/pull/258#issuecomment-76958258

不知道大家對於這個有無其他建議？

https://github.com/iojs/website/blob/template-build-refactor_i18n-footer/source/project.json#L22

```
{"code": "zh_TW", "name": "台灣", "name-en": "Chinese (Taiwan)"}
```

**Comment by popomore** [comment]
我覺得可以改成简体中文和繁體中文

**Comment by mingtsay** [comment]
{"code": "zh_TW", "name": "正體中文（台灣）", "name-en": "Chinese Traditional
(Taiwan)"}

這樣如何？

**Comment by poying** [comment]
@mingtsay  +1

**Comment by PeterDaveHello** [comment]
@mingtsay +1

**Comment by lepture** [comment]
@mingtsay @poying 

正體的說法不太友好，「簡體」對應的應該是「繁體」。「正體」的說法有一種標準的意思。

**Comment by jihchi** [comment]
@mingtsay +1

**Comment by josyeh** [comment]
正體 +1

**Comment by dca** [comment]
@lepture 

請問「正體」不友好的點是在哪呢？
英文說： traditional chinese 是不是就比較類似「正體」呢？

另外，這樣「繁體」的說法是不是會有一種複雜、繁瑣的意思？

**Comment by poying** [comment]
@dca 我想 @lepture 的意思跟這篇文章有點類似
https://www.byvoid.com/blog/chinese-character-definition

「......正體字本是相對於異體字的概念。眾所周知，漢字創造年代久遠，且絕非一人、一時創造。故表達同一個意思，可能有多種寫法，這就是異體字。......」
「......由此可見，漢字可能會一字多體，在多體中選擇一體爲「正體」，那麼其他的字就都是異體。......」

**Comment by lepture** [comment]
@poying 大致如此，而且臺灣用字並不「正」。不過無所謂啦，如果大家覺得用「正體」好，那就用「正體」吧。

**Comment by jessy1092** [comment]
官方名稱: 正體中文

`「國字」、「正體字」、「標準字」是臺灣對傳統漢字的官方名稱`

ref. http://www.wikiwand.com/zh-hant/%E7%B9%81%E4%BD%93%E4%B8%AD%E6%96%87

**Comment by appleboy** [comment]
老實說我不太確定官方會不會讓我們使用這麼長的名稱 XD

**Comment by jessy1092** [comment]
上線了 https://iojs.org/zh_TW/index.html   正體中文（台灣）!!!!!!   XD

**Comment by poying** [comment]
好其為什麼兩個中文被分這麼開，一個在頭，一個在尾 XD

**Comment by mingtsay** [comment]
cn 的 C 跟 zh_TW 的 Z 的差距嗎ww

**Comment by popomore** [comment]
英文首字母排序吧

**Comment by appleboy** [comment]
大家幫忙按一下贊 https://github.com/iojs/website/pull/275

:+1:

**Comment by appleboy** [comment]
官方已經修正了，關閉 Issue.
