### ISSUE TITLE
io.js Week of March 6th

### ISSUE THREAD

**Issue by chentsulin** [nodejs/iojs-tw#60]
原文：
https://medium.com/node-js-javascript/io-js-week-of-march-6th-2f9344688277

**Comment by chentsulin** [comment]
已新增草稿在 source/_drafts

**Comment by appleboy** [comment]
@chentsulin Thanks

**Comment by appleboy** [comment]
@Ferrari @chentsulin 感謝大家的幫忙，已經發佈最新的 weekly notes

http://tw.iojs.org/2015/03/08/weekly-update-2015-03-06/

cc @iojs/iojs-tw
