### ISSUE TITLE
iojs-tw 官網增加 github 連結

### ISSUE THREAD

**Issue by jessy1092** [nodejs/iojs-tw#63]
目前 iojs-tw 官網，並沒有相關連結，連接到 github 上的工作群。

如果加上 github 連結，應該可以吸引看完文章，然後想幫忙的開發者或是一些建議回饋。

cc @appleboy 
#23

**Comment by PeterDaveHello** [comment]
加個Github ribbon或是在footer放個聯結？

**Comment by clonn** [comment]
之前好像有看到跟這個相關的 pr ，怎麼好像不見了 XDDDDD

**Comment by appleboy** [comment]
之前最初的 theme 有包含 about me 單一 page，後來換了風格後，該風格沒有 single page.

https://github.com/iojs/iojs-tw/blob/master/source/about-us/index.md

要自己修改 theme 才可以

**Comment by appleboy** [comment]
各位建議放在 footer 嗎？

![screen shot 2015-03-14 at 9 13 16 pm](https://cloud.githubusercontent.com/assets/21979/6651770/ff198dd8-ca8e-11e4-88a0-d7636daa9565.png)

如果沒問題我就放上圖這位置，大家有覺得要放上哪些連結？

**Comment by siygle** [comment]
+1

**Comment by jessy1092** [comment]
:+1: 

Twitter: https://twitter.com/iojs_tw

**Comment by appleboy** [comment]
Hi all,

我把 github 連結放在左上角，看看大家覺得OK嘛？

http://iojs.nodejs.tw/

cc @iojs/iojs-tw

**Comment by siygle** [comment]
好像比較常放在右邊!?
不過應該也沒關係 XDD

**Comment by appleboy** [comment]
因為我覺得左邊有點空，右邊有一個很大的 Node.js XD

**Comment by appleboy** [comment]
有問題再另外提出
