### ISSUE TITLE
NPM weekly 8

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#64]
http://blog.npmjs.org/post/113262605295/npm-weekly-8

已經放上原版英文的 Draft

https://github.com/iojs/iojs-tw/blob/master/source/_drafts/npm-weekly-8.md

**Comment by clonn** [comment]
先跳出來當沒有人，如果覺得有哪邊需要修正，再接著進行。 :D

**Comment by appleboy** [comment]
https://github.com/iojs/iojs-tw/commit/2bc002e765d8f3a3e4554812a61143a2b8cc6e6f

@clonn Thanks.

**Comment by appleboy** [comment]
cc @iojs/iojs-tw
