### ISSUE TITLE
weekly update March 13th

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#66]
https://github.com/iojs/evangelism/pull/44

**Comment by chentsulin** [comment]
已知 Issue 大部份都跟上禮拜一樣

**Comment by appleboy** [comment]
放上原文了

https://medium.com/node-js-javascript/io-js-week-of-march-13th-e3024cc66802

**Comment by appleboy** [comment]
http://tw.iojs.org/2015/03/15/weekly-update-march-13th/

Done! Thanks @chentsulin and @Ferrari 

cc @iojs/iojs-tw
