### ISSUE TITLE
協助翻譯 iojs weekly 資料

### ISSUE THREAD

**Issue by clonn** [nodejs/iojs-tw#8]
目前先以翻譯官方 weekly 資料，可參考資料如下，
- [iojs weekly](https://medium.com/@iojs)
- [iojs-cn weekly](https://github.com/iojs/iojs-cn/tree/master/weekly)

目前直接放置於 `iojs-tw/weekly` 為主，歡迎 [填寫入坑名單](https://github.com/iojs/iojs-tw/issues/2)

**Comment by cfsghost** [comment]
以後只要有原文文章被發布，就可以發 issue 出來，然後要翻譯的人可以先搶先贏。

如果沒空翻全部的人，可以翻部分文字於 issue 上。

**Comment by appleboy** [comment]
同意 @cfsghost 想翻的人先搶先贏了，issue number 越小為主 XD

**Comment by clonn** [comment]
那先以這個模式定案，把此討論 close
