### ISSUE TITLE
協助翻譯 io.js 網頁翻譯成繁體資料

### ISSUE THREAD

**Issue by clonn** [nodejs/iojs-tw#9]
io.js 官方網站將會轉成 i18n ，需要協助翻譯成繁體語系內容。

需要協助內容，需要協助翻譯，將統一由 nodejs-taiwan 這邊對 io.js 進行 pull request.
- [index page](https://github.com/nodejs-tw/website/blob/i18n-static/public/i18n/tw/index.html)
- [faq page](https://github.com/nodejs-tw/website/blob/i18n-static/public/i18n/tw/faq.html)
- [es6 page](https://github.com/nodejs-tw/website/blob/i18n-static/public/i18n/tw/es6.html)

**Comment by cfsghost** [comment]
話說，我晚上就開始在慢慢翻了，剛剛完成，並送出第一版的 io.js PR 了。XD

https://github.com/iojs/website/pull/135

**Comment by appleboy** [comment]
幫忙把 `FAQ` 翻譯成`常見問題` 

https://github.com/iojs/iojs-tw/commit/771d7120406375d2f1b24f3746cbd2fd6cd96fa2

@cfsghost 可以幫忙 merge 到你那邊的 Repo？

**Comment by poying** [comment]
@appleboy @cfsghost 後續又有兩個小修正

**Comment by cfsghost** [comment]
Merged

**Comment by clonn** [comment]
既然已經 merged ，看來可以先 close
