### ISSUE TITLE
npm 週報 14

### ISSUE THREAD

**Issue by appleboy** [nodejs/iojs-tw#98]
http://tw.iojs.org/2015/04/30/npm-weekly-14/

已經翻譯完成，請大家幫忙看看

cc @jihchi @Ferrari

**Comment by siygle** [comment]
>  Apache Cordova announced that it will use npm for its core plugins and is encouraging plugin developers to do the same.

這句是不是翻成「Apache Cordova 宣布將其核心套件轉移到 npm，也鼓勵插件開發者這麼做」會比較接近原意!?

> Jessica Lord 寫了一個簡單範例)在 git-it 套件內

這邊好像多了個 ")"

**Comment by appleboy** [comment]
https://github.com/iojs/iojs-tw/commit/ffc7939822a283c903491db989daf2640911ec90

已修正

**Comment by appleboy** [comment]
還有其他問題可以直接發 PR，先關掉此 issue。
